# Generated by Django 3.2.3 on 2021-06-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_purchase_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=81)),
                ('phone', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=81)),
                ('street', models.CharField(max_length=81)),
                ('house', models.CharField(max_length=81)),
                ('flat', models.CharField(max_length=81)),
                ('date', models.DateTimeField()),
                ('commentary', models.TextField(blank=True, null=True)),
                ('pay', models.CharField(max_length=81)),
                ('products', models.ManyToManyField(related_name='products_orders', to='api.Purchase')),
            ],
        ),
    ]
