# Generated by Django 3.2.3 on 2021-06-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay',
            field=models.CharField(default='Наличными', max_length=81),
        ),
    ]
